# 파일 다루기
- 파일 열기 open(), with로 열기
- csv, xlsx 파일 다루기
- zip 파일 다루기
- 폴더 내 파일 목록 다루기 (glob, listdir)
- 폴더/파일 생성과 삭제

## import

In [1]:
import pandas as pd
import numpy as np
from numpy.random import rand
import csv
import os
from glob import glob

##  숫자 데이터  파일 생성
- 센서 데이터 등 어레이 데이터를 csv 파일로 저장하기

### 단일 센서 데이터

In [2]:
x1 = np.random.rand(10)
x1

array([0.11071104, 0.3723322 , 0.76446916, 0.6496964 , 0.10484002,
       0.72358426, 0.91973207, 0.83933865, 0.56762904, 0.15661023])

In [ ]:
np.savetxt("test_1.csv", x1, delimiter=",")

### 파일 내용 출력
- read()와 print() 함수 사용
- !cat, !type 등 명령어를 사용하지 않아도 됨

In [3]:
with open('test_1.csv') as f: 
    print(f.read())

1.107110385301496303e-01
3.723322007280938095e-01
7.644691628575618347e-01
6.496963981335130978e-01
1.048400156893453117e-01
7.235842569714772132e-01
9.197320732977386504e-01
8.393386521959560476e-01
5.676290411512473488e-01
1.566102323840932176e-01

In [4]:
# 데이터프레임으로 읽기
df1 = pd.read_csv('test_1.csv', header=None)  
df1

          0
0  0.110711
1  0.372332
2  0.764469
3  0.649696
4  0.104840
5  0.723584
6  0.919732
7  0.839339
8  0.567629
9  0.156610

### 5개의 센서 데이터

In [5]:
# (10,5) 구조의 데이터
x2 = np.arange(50).reshape(10,5)
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
np.savetxt("test_2.csv", x2, delimiter=",")

In [47]:
df = pd.read_csv('test_2.csv', header=None)  
df
# 디폴트로 첫 행을 컬럼명으로 인식한다, 컬럼명 행이 없다는 것을 명시해야 한다

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

In [8]:
# 어레이로 변환하기
df.values

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

### read_csv 옵션
 - nrows=10 (상위 10줄만 읽기)
 - skiprows = 10 (10줄 건너뛰기)
 - skiprows = (1,2,5) (1, 2, 5행 건너뛰기)
 - skipfooter = 1000 (맨 뒤의 1000줄 읽지 않기)
 - usecols= (0,2,4) (해당 컬럼만 읽는다)

In [9]:
# 일부 행만 읽기 nrows 사용 (3줄 읽기)
df2 = pd.read_csv('test_2.csv', nrows=3, header=None)
df2

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0

In [10]:
df2 = pd.read_csv('test_2.csv', skiprows=3, header=None)
df2

      0     1     2     3     4
0  15.0  16.0  17.0  18.0  19.0
1  20.0  21.0  22.0  23.0  24.0
2  25.0  26.0  27.0  28.0  29.0
3  30.0  31.0  32.0  33.0  34.0
4  35.0  36.0  37.0  38.0  39.0
5  40.0  41.0  42.0  43.0  44.0
6  45.0  46.0  47.0  48.0  49.0

In [49]:
df2 = pd.read_csv('test_2.csv', skiprows=(1,3), header=None)
df2

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1  10.0  11.0  12.0  13.0  14.0
2  20.0  21.0  22.0  23.0  24.0
3  25.0  26.0  27.0  28.0  29.0
4  30.0  31.0  32.0  33.0  34.0
5  35.0  36.0  37.0  38.0  39.0
6  40.0  41.0  42.0  43.0  44.0
7  45.0  46.0  47.0  48.0  49.0

In [12]:
df2 = pd.read_csv('test_2.csv', skipfooter=6, header=None)
df2

<ipython-input-12-04ade2a62137>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df2 = pd.read_csv('test_2.csv', skipfooter=6, header=None)

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

## 어레이로 바로 읽기
- 데이터 크기가 크면 데이터프레임을 만드는데 시간이 많이 걸린다

In [13]:
array_data = np.genfromtxt('test_2.csv', delimiter=',')
array_data

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

In [14]:
# 일부 라인만 읽기 (데이터가 너무 클 때)
np.genfromtxt('test_2.csv', delimiter=',', max_rows=5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [48]:
# 일부 컬럼만 읽을 때
np.genfromtxt('test_2.csv', delimiter=',', usecols=(0,2,4))

array([[ 0.,  2.,  4.],
       [ 5.,  7.,  9.],
       [10., 12., 14.],
       [15., 17., 19.],
       [20., 22., 24.],
       [25., 27., 29.],
       [30., 32., 34.],
       [35., 37., 39.],
       [40., 42., 44.],
       [45., 47., 49.]])

## csv 파일로 출력
- 판다스의 to_csv() 사용

In [15]:
df = pd.read_csv('test_2.csv', header=None)  
df

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

In [16]:
df.to_csv('output.csv')
with open('output.csv') as f: print(f.read())

,0,1,2,3,4
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0
4,20.0,21.0,22.0,23.0,24.0
5,25.0,26.0,27.0,28.0,29.0
6,30.0,31.0,32.0,33.0,34.0
7,35.0,36.0,37.0,38.0,39.0
8,40.0,41.0,42.0,43.0,44.0
9,45.0,46.0,47.0,48.0,49.0

- 데이터 프레임의 인덱스와 컬럼도 포함되어 저장된다
- 인덱스를 제거하려면, index=False 를 지정한다

In [17]:
df.to_csv('output.csv', index=False, header=False)
with open('output.csv') as f: print(f.read())

0.0,1.0,2.0,3.0,4.0
5.0,6.0,7.0,8.0,9.0
10.0,11.0,12.0,13.0,14.0
15.0,16.0,17.0,18.0,19.0
20.0,21.0,22.0,23.0,24.0
25.0,26.0,27.0,28.0,29.0
30.0,31.0,32.0,33.0,34.0
35.0,36.0,37.0,38.0,39.0
40.0,41.0,42.0,43.0,44.0
45.0,46.0,47.0,48.0,49.0

## 액셀 파일로 출력

In [18]:
df.to_excel('output.xlsx', index=False, header=False)
pd.read_excel('output.xlsx', header=None)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

### 액셀 한글 인코딩
- 문자의 인코딩은 기본적으로 utf-8 을 사용한다
- 그러나 한글의 경우 다른 인코딩으로 저장되는 경우가 있다
 - MS 액셀에서 csv로 저장할 때 한글이 cpc949로 인코딩된다. 이때는 아래 옵션이 필요하다
 - encoding = 'cpc949'
 - encoding = 'EUK-KR'을 선택해야 하는 경우도 있다

## zip 파일 
### zip 파일 만들기
- output.csv 을 output.zip로 압축하는 경우

In [19]:
import zipfile
with zipfile.ZipFile('output.zip', 'w') as z:
    z.write('output.csv')

### zip 파일 풀기

In [20]:
with zipfile.ZipFile("output.zip", 'r') as z: 
    print(z.namelist()) # zip에 포한된 파일목록 보기
    z.extractall() # 압축 풀기, 하위 폴더 지정 가능

['output.csv']

- zip 파일은 read_csv에서 바로 읽을 수 있다 (압축을 풀 필요 없다)

In [21]:
pd.read_csv('output.zip', header=None)

      0     1     2     3     4
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4  20.0  21.0  22.0  23.0  24.0
5  25.0  26.0  27.0  28.0  29.0
6  30.0  31.0  32.0  33.0  34.0
7  35.0  36.0  37.0  38.0  39.0
8  40.0  41.0  42.0  43.0  44.0
9  45.0  46.0  47.0  48.0  49.0

# 폴더 작업

## 현재 폴더 위치 보기

In [22]:
import os
cur_dir = os.getcwd()
cur_dir

'/Users/hjk/Dropbox/lab/book12'

## 폴더의 파일 목록 얻기
- glob() 사용
- listdir() 사용

### glob()를 사용

In [23]:
# 파일 목록 얻기
from glob import glob
sorted(glob('*.ipynb'))

['32SlidingWindow2-210915.ipynb',
 '32SlidingWindow2_211005_X10.ipynb',
 '32SlidingWindow2_211005_X8.ipynb',
 '32SlidingWindow2_211005_X9.ipynb',
 'DT전문가_S3사후과제_일렉트릭_박아련.ipynb',
 'DX_Motor.ipynb',
 'PM_Exersize_210805.ipynb',
 'PM_Exersize_210805_정답.ipynb',
 'Project_Life_Expectancy.ipynb',
 'SET_angle_V2.ipynb',
 'Untitled.ipynb',
 'Untitled0.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'aa_08_Boston_Opt.ipynb',
 'd_01_Python.ipynb',
 'd_02_Pandas.ipynb',
 'd_03_Numpy.ipynb',
 'd_04_File.ipynb',
 'd_04_FileFolder.ipynb',
 'd_04_기초통계.ipynb',
 'f-outlier-detection.ipynb',
 'f_01_Python.ipynb',
 'f_02_1_Pandas_tips.ipynb',
 'f_02_Pandas.ipynb',
 'f_03_Numpy.ipynb',
 'f_04_File.ipynb',
 'f_05_Function.ipynb',
 'f_06_Preprocessing.ipynb',
 'f_07_Preprocessing_Example.ipynb',
 'f_08_Table.ipynb',
 'f_09_Groupby.ipynb',
 'f_10_LinearPrediction-RF.ipynb',
 'f_10_LinearPrediction.ipynb',
 'f_10_TS_Forecasting.ipynb',
 'f_11_MachineLearning.ipynb',
 'f_12_GD.ipynb',
 'f_13_Classification.ipynb',
 'f_15_LogisticRegression.ipynb',
 'f_16_Ranking_proba.ipynb',
 'f_18_SVM.ipynb',
 'f_19_ModelComparison.ipynb',
 'f_20_Ensemble-Copy1.ipynb',
 'f_20_Ensemble.ipynb',
 'f_21_StatisticsBasic.ipynb',
 'f_22_FeatureEngineering.ipynb',
 'f_25_MultiOutput.ipynb',
 'f_26_TimeseriesOutput.ipynb',
 'f_27_TimeseriesForecasting.ipynb',
 'f_29_ProphetAdvanced.ipynb',
 'f_30_AddFeatures.ipynb',
 'f_31_XY_Model.ipynb',
 'f_32_PM.ipynb',
 'f_33_MLP_CNN-Copy1.ipynb',
 'f_33_MLP_CNN.ipynb',
 'f_34_PatternRecognition.ipynb',
 'f_35_Image_Recognition.ipynb',
 'f_36_TransferLearning.ipynb',
 'f_37_LSTM.ipynb',
 'f_38_LSTM_TimeSeries.ipynb',
 'f_39_YOLO.ipynb',
 'f_40_YOLO_FineTuning.ipynb',
 'f_41_opencv_face.ipynb',
 'f_42_opencv_digit.ipynb',
 'f_43_object_detect.ipynb',
 'f_44_LP.ipynb',
 'f_45_IntegerLP.ipynb',
 'f_46_MatrixLP.ipynb',
 'f_47_Constraint.ipynb',
 'f_48_Assignment.ipynb',
 'f_49_Routing.ipynb',
 'f_50_LP_Example.ipynb',
 'f_51_GoldPriceipynb.ipynb',
 'f_53_CustomerSegmentation.ipynb',
 'f_54_BankChurnAnalysis.ipynb',
 'f_55_DefaultPrediction.ipynb',
 'f_56_CreditcardFraudDetection.ipynb',
 'f_57_Collaborative_Filtering.ipynb',
 'f_58_movie_generate.ipynb',
 'f_59_Recommender_system_SVD.ipynb',
 'f_90_opencv_perspective.ipynb',
 'f_91_Dash.ipynb',
 'f_91_Recommendation_surprise.ipynb',
 'f_99_Practice.ipynb',
 'f_Old_14_Ranking_PRCurve.ipynb',
 'f_Old_life-expectancy-who-with-several-ml-techniques.ipynb',
 'f_Old_walmart-sales-forecast.ipynb',
 'f_textbook_1.ipynb',
 'fn_0_Utility.ipynb',
 'fn_11_Regression.ipynb',
 'fn_13_Classification.ipynb',
 'fn_14_Ranking_PRCurve.ipynb',
 'fn_15_LogisticRegression.ipynb',
 'fn_17_DecisionTree_RF.ipynb',
 'fn_19_Models.ipynb',
 'fn_23_Clustering.ipynb',
 'fn_24_ClusteringExample.ipynb',
 'fn_27_TimeseriesForecasting.ipynb',
 'fn_28_Prophet.ipynb',
 'fn_51_walmart-store-sales-forecasting.ipynb',
 'fn_52_StockData.ipynb',
 'g_45_yolo.ipynb',
 'g_46_Yolo5_ing.ipynb',
 'g_54_토픽모델링.ipynb',
 'g_60_6_비클라우팅.ipynb',
 'g_60_7_라우팅고급.ipynb',
 'g_60_8_OR_응용.ipynb',
 'g_61_1_물류최적화개념.ipynb',
 'g_61_2_물류최적화.ipynb',
 'g_63_LP기초.ipynb',
 'g_71_1_Molecular_Visualization_using_RDkit.ipynb',
 'g_71_2_DeepChem_라이브러리를_활용한Solubility_Modeling.ipynb',
 'g_71_3_Pytorch를_사용한_QSAR_모델_구축Prediction.ipynb',
 'g_71_4_Pytorch를_사용한_QSAR_모델_구축Classification.ipynb',
 'g_71_5_GraphDTA_ipynb_.ipynb',
 'g_81_스트링_객체변환.ipynb',
 'g_84_flask.ipynb',
 'h_00_쥬피터노트북.ipynb',
 'h_01_파이썬기초.ipynb',
 'h_02_pandas.ipynb',
 'h_03_numpy.ipynb',
 'h_04_1_파일다루기연습.ipynb',
 'h_04_파일다루기.ipynb',
 'h_05_함수사용.ipynb',
 'h_06_데이터전처리.ipynb',
 'h_07_데이터전처리실습.ipynb',
 'h_08_탐색적분석.ipynb',
 'h_09_테이블다루기.ipynb',
 'h_10_시계열데이터처리.ipynb',
 'h_11_머신러닝개요.ipynb',
 'h_12_회귀모델.ipynb',
 'h_12_회귀모델_210711.ipynb',
 'h_13_분류모델.ipynb',
 'h_14_분류순위평가.ipynb',
 'h_15_통계분석과머신러닝.ipynb',
 'h_16_로지스틱회귀.ipynb',
 'h_17_머신러닝모델비교_210702.ipynb',
 'h_18_분류예제_포도주.ipynb',
 'h_19_0_다중출력회귀_210712.ipynb',
 'h_19_1_다중출력회귀시계열_210712.ipynb',
 'h_20_앙상블알고리즘_0624.ipynb',
 'h_21_XGBoost_LightGBM_0704.ipynb',
 'h_23_차원축소_특성공학.ipynb',
 'h_24_Imbalance_CreditCard.ipynb',
 'h_25_클러스터링기초.ipynb',
 'h_26_클러스터링_최적_k.ipynb',
 'h_27_0_시계열분석기초.ipynb',
 'h_27_1_시계열 특성추가_210701.ipynb',
 'h_28_prophet.ipynb',
 'h_31_자전거대여수예측_0701.ipynb',
 'h_32_Prophet_응용.ipynb',
 'h_33_PM_210717.ipynb',
 'h_34_1_MLP_CNN_210418.ipynb',
 'h_34_LSTM_기본개념.ipynb',
 'h_34_시계열_rnn_전력사용예측.ipynb',
 'h_35_시퀀스패턴분류_210703_.ipynb',
 'h_36_1_디지털필터출력.ipynb',
 'h_37_이미지인식_210418_ipynb.ipynb',
 'h_38_전이학습.ipynb',
 'h_39_opencv_face-Copy1.ipynb',
 'h_42_뉴스기사분석.ipynb',
 'h_43_스팸분류.ipynb',
 'h_44_네이버영화평점.ipynb',
 'h_45_형태소분석.ipynb',
 'h_46_단어벡터.ipynb',
 'h_47_IMDB_Embedding.ipynb',
 'h_48_언어모델링.ipynb',
 'h_80_웹크롤링.ipynb',
 'h_81_YOLOv5_Tutorial.ipynb',
 'h_82_YOLOv5_Fine_Tuning.ipynb',
 'h_83_Dash소개.ipynb',
 'h_90_Autoencoders_MNIST.ipynb',
 'h_90_ML_overview.ipynb',
 'h_90_SECOM_불량검출.ipynb',
 'h_90_inspect_pill.ipynb',
 'h_90_series_clustering.ipynb',
 'h_90_telemetry.ipynb',
 'h_90_경사하강법구현.ipynb',
 'h_90_총판매량예측_prophet.ipynb',
 'h_90_판매량예측_LSTM.ipynb',
 'h_92_대용량텍스트데이터처리.ipynb',
 'h_94_groupby_0717.ipynb',
 'h_etc.ipynb',
 'h_filter_design.ipynb',
 'h_강의개요 Part 2-3.ipynb',
 'h_참조11_액셀파일다루기.ipynb',
 'h_참조11_테이블데이터다루기(팁).ipynb',
 'h_추가할 것.ipynb',
 'h_파일리스트.ipynb',
 'hh_17_머신러닝모델비교.ipynb',
 'hh_19_고객이탈예측.ipynb',
 'hh_20_ensemble.ipynb',
 'hh_20_앙상블알고리즘.ipynb',
 'hh_27_1_시계열 특성추가.ipynb',
 'hh_27_1_시계열 특성추가_210628.ipynb',
 'hh_29_시계열예측_자전거대여.ipynb',
 'hh_31_시계열예측모델비교.ipynb',
 'hh_33_PM_210531.ipynb',
 'hh_34_ARIMA.ipynb',
 'hh_34_LSTM_가정전력예측.ipynb',
 'hh_34_PM_LSTM.ipynb',
 'hh_34_PM_LSTM2_210418.ipynb',
 'hh_34_telemetry.ipynb',
 'hh_34_가정전기사용량EDA.ipynb',
 'hh_34_수퍼마켓판매량예측_LSTM.ipynb',
 'hh_34_시계열MLP_선형비교.ipynb',
 'hh_34_시계열_rnn_사인파.ipynb',
 'hh_34_오염예측_LSTM.ipynb',
 'hh_34_전기사용예측_prophet.ipynb',
 'hh_34_전력데이터_MS_RNN-2.ipynb',
 'hh_34_전력데이터_MS_RNN.ipynb',
 'hh_36_신경망기초_MLP_CNN.ipynb',
 'hh_37_이미지인식.ipynb',
 'hh_83_DashBoard.ipynb',
 'life.ipynb',
 'make_blur_noise (1).ipynb',
 'plot_Filtering.ipynb',
 'test.ipynb',
 'web.ipynb',
 '신용재_소스코드로제출.ipynb']

### listdir()를 사용

In [24]:
# 파일과 폴더 목록 얻기
file_list = os.listdir()
sorted(file_list)

['.DS_Store',
 '.ipynb_checkpoints',
 '.tmp.drivedownload',
 '32SlidingWindow0928update.xlsx',
 '32SlidingWindow2-210915.ipynb',
 '32SlidingWindow2.xlsx',
 '32SlidingWindow2_211005_X10.ipynb',
 '32SlidingWindow2_211005_X8.ipynb',
 '32SlidingWindow2_211005_X9.ipynb',
 'A.csv',
 'B.csv',
 'C.csv',
 'DS-210905.hwp',
 'DS-210907-대학원-1.hwp',
 'DS-210907-대학원-1.pdf',
 'DT전문가_S3사후과제_일렉트릭_박아련.ipynb',
 'DX_Motor.ipynb',
 'Gold Prices.xlsx',
 'HE_0722.zip',
 'HE_Project_Examples.zip',
 'Hands-on-Python-for-Finance-master',
 'Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash-master',
 'LGadd2',
 'LGadd2.zip',
 'LS DT전문가_최종과제_취합',
 'Life Expectancy Data.csv',
 'Merged_excel.xlsx',
 'NGdata1.zip',
 'PM_Exersize_210805.ipynb',
 'PM_Exersize_210805_정답.ipynb',
 'PM_train_pre.csv',
 'Project_Life_Expectancy.ipynb',
 'Python-for-Finance-Cookbook-master',
 'Refr.csv',
 'SET_angle_V2.ipynb',
 'TV.csv',
 'Untitled.ipynb',
 'Untitled0.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 '__MACOSX',
 'aa_08_Boston_Opt.ipynb',
 'big.csv',
 'chromedriver',
 'cities.csv',
 'cities.xlsx',
 'competitive-data-science-predict-future-sales',
 'credit.csv.zip',
 'creditcard.csv',
 'customer.csv',
 'd_01_Python.ipynb',
 'd_02_Pandas.ipynb',
 'd_03_Numpy.ipynb',
 'd_04_File.ipynb',
 'd_04_FileFolder.ipynb',
 'd_04_기초통계.ipynb',
 'data',
 'datasalon-master',
 'df_excelwriter.xlsx',
 'df_sample.json',
 'digit2.png',
 'digit9-2.png',
 'digit9.png',
 'digits-lin.pkl',
 'digits.pkl',
 'down.zip',
 'down2.zip',
 'eCar.csv',
 'energy.csv',
 'f-outlier-detection.ipynb',
 'f_01_Python.ipynb',
 'f_02_1_Pandas_tips.ipynb',
 'f_02_Pandas.ipynb',
 'f_03_Numpy.ipynb',
 'f_04_File.ipynb',
 'f_05_Function.ipynb',
 'f_06_Preprocessing.ipynb',
 'f_07_Preprocessing_Example.ipynb',
 'f_08_Table.ipynb',
 'f_09_Groupby.ipynb',
 'f_10_LinearPrediction-RF.ipynb',
 'f_10_LinearPrediction.ipynb',
 'f_10_TS_Forecasting.ipynb',
 'f_11_MachineLearning.ipynb',
 'f_12_GD.ipynb',
 'f_13_Classification.ipynb',
 'f_15_LogisticRegression.ipynb',
 'f_16_Ranking_proba.ipynb',
 'f_18_SVM.ipynb',
 'f_19_ModelComparison.ipynb',
 'f_20_Ensemble-Copy1.ipynb',
 'f_20_Ensemble.ipynb',
 'f_21_StatisticsBasic.ipynb',
 'f_22_FeatureEngineering.ipynb',
 'f_25_MultiOutput.ipynb',
 'f_26_TimeseriesOutput.ipynb',
 'f_27_TimeseriesForecasting.ipynb',
 'f_29_ProphetAdvanced.ipynb',
 'f_30_AddFeatures.ipynb',
 'f_31_XY_Model.ipynb',
 'f_32_PM.ipynb',
 'f_33_MLP_CNN-Copy1.ipynb',
 'f_33_MLP_CNN.ipynb',
 'f_34_PatternRecognition.ipynb',
 'f_35_Image_Recognition.ipynb',
 'f_36_TransferLearning.ipynb',
 'f_37_LSTM.ipynb',
 'f_38_LSTM_TimeSeries.ipynb',
 'f_39_YOLO.ipynb',
 'f_40_YOLO_FineTuning.ipynb',
 'f_41_opencv_face.ipynb',
 'f_42_opencv_digit.ipynb',
 'f_43_object_detect.ipynb',
 'f_44_LP.ipynb',
 'f_45_IntegerLP.ipynb',
 'f_46_MatrixLP.ipynb',
 'f_47_Constraint.ipynb',
 'f_48_Assignment.ipynb',
 'f_49_Routing.ipynb',
 'f_50_LP_Example.ipynb',
 'f_51_GoldPriceipynb.ipynb',
 'f_53_CustomerSegmentation.ipynb',
 'f_54_BankChurnAnalysis.ipynb',
 'f_55_DefaultPrediction.ipynb',
 'f_56_CreditcardFraudDetection.ipynb',
 'f_57_Collaborative_Filtering.ipynb',
 'f_58_movie_generate.ipynb',
 'f_59_Recommender_system_SVD.ipynb',
 'f_90_opencv_perspective.ipynb',
 'f_91_Dash.ipynb',
 'f_91_Recommendation_surprise.ipynb',
 'f_99_Practice.ipynb',
 'f_Old_14_Ranking_PRCurve.ipynb',
 'f_Old_life-expectancy-who-with-several-ml-techniques.ipynb',
 'f_Old_walmart-sales-forecast.ipynb',
 'f_textbook_1.ipynb',
 'face-detect.png',
 'face-pickup.png',
 'families.jpg',
 'features.csv.zip',
 'fn_0_Utility.ipynb',
 'fn_11_Regression.ipynb',
 'fn_13_Classification.ipynb',
 'fn_14_Ranking_PRCurve.ipynb',
 'fn_15_LogisticRegression.ipynb',
 'fn_17_DecisionTree_RF.ipynb',
 'fn_19_Models.ipynb',
 'fn_23_Clustering.ipynb',
 'fn_24_ClusteringExample.ipynb',
 'fn_27_TimeseriesForecasting.ipynb',
 'fn_28_Prophet.ipynb',
 'fn_51_walmart-store-sales-forecasting.ipynb',
 'fn_52_StockData.ipynb',
 'g_45_yolo.ipynb',
 'g_46_Yolo5_ing.ipynb',
 'g_54_토픽모델링.ipynb',
 'g_60_6_비클라우팅.ipynb',
 'g_60_7_라우팅고급.ipynb',
 'g_60_8_OR_응용.ipynb',
 'g_61_1_물류최적화개념.ipynb',
 'g_61_2_물류최적화.ipynb',
 'g_63_LP기초.ipynb',
 'g_71_1_Molecular_Visualization_using_RDkit.ipynb',
 'g_71_2_DeepChem_라이브러리를_활용한Solubility_Modeling.ipynb',
 'g_71_3_Pytorch를_사용한_QSAR_모델_구축Prediction.ipynb',
 'g_71_4_Pytorch를_사용한_QSAR_모델_구축Classification.ipynb',
 'g_71_5_GraphDTA_ipynb_.ipynb',
 'g_81_스트링_객체변환.ipynb',
 'g_84_flask.ipynb',
 'gg_74_시계열기초LSTM.ipynb 복사본',
 'gg_79_전력사용시계열분석.ipynb 복사본',
 'gold_price.csv',
 'h_00_쥬피터노트북.ipynb',
 'h_01_파이썬기초.ipynb',
 'h_02_pandas.ipynb',
 'h_03_numpy.ipynb',
 'h_04_1_파일다루기연습.ipynb',
 'h_04_파일다루기.ipynb',
 'h_05_함수사용.ipynb',
 'h_06_데이터전처리.ipynb',
 'h_07_데이터전처리실습.ipynb',
 'h_08_탐색적분석.ipynb',
 'h_09_테이블다루기.ipynb',
 'h_10_시계열데이터처리.ipynb',
 'h_11_머신러닝개요.ipynb',
 'h_12_회귀모델.ipynb',
 'h_12_회귀모델_210711.ipynb',
 'h_13_분류모델.ipynb',
 'h_14_분류순위평가.ipynb',
 'h_15_통계분석과머신러닝.ipynb',
 'h_16_로지스틱회귀.ipynb',
 'h_17_머신러닝모델비교_210702.ipynb',
 'h_18_분류예제_포도주.ipynb',
 'h_19_0_다중출력회귀_210712.ipynb',
 'h_19_1_다중출력회귀시계열_210712.ipynb',
 'h_20_앙상블알고리즘_0624.ipynb',
 'h_21_XGBoost_LightGBM_0704.ipynb',
 'h_23_차원축소_특성공학.ipynb',
 'h_24_Imbalance_CreditCard.ipynb',
 'h_25_클러스터링기초.ipynb',
 'h_26_클러스터링_최적_k.ipynb',
 'h_27_0_시계열분석기초.ipynb',
 'h_27_1_시계열 특성추가_210701.ipynb',
 'h_28_prophet.ipynb',
 'h_31_자전거대여수예측_0701.ipynb',
 'h_32_Prophet_응용.ipynb',
 'h_33_PM_210717.ipynb',
 'h_34_1_MLP_CNN_210418.ipynb',
 'h_34_LSTM_기본개념.ipynb',
 'h_34_시계열_rnn_전력사용예측.ipynb',
 'h_35_시퀀스패턴분류_210703_.ipynb',
 'h_36_1_디지털필터출력.ipynb',
 'h_37_이미지인식_210418_ipynb.ipynb',
 'h_38_전이학습.ipynb',
 'h_39_opencv_face-Copy1.ipynb',
 'h_42_뉴스기사분석.ipynb',
 'h_43_스팸분류.ipynb',
 'h_44_네이버영화평점.ipynb',
 'h_45_형태소분석.ipynb',
 'h_46_단어벡터.ipynb',
 'h_47_IMDB_Embedding.ipynb',
 'h_48_언어모델링.ipynb',
 'h_80_웹크롤링.ipynb',
 'h_81_YOLOv5_Marking.pptx',
 'h_81_YOLOv5_Tutorial.ipynb',
 'h_82_YOLOv5_Fine_Tuning.ipynb',
 'h_83_Dash소개.ipynb',
 'h_90_Autoencoders_MNIST.ipynb',
 'h_90_ML_overview.ipynb',
 'h_90_SECOM_불량검출.ipynb',
 'h_90_inspect_pill.ipynb',
 'h_90_series_clustering.ipynb',
 'h_90_telemetry.ipynb',
 'h_90_경사하강법구현.ipynb',
 'h_90_총판매량예측_prophet.ipynb',
 'h_90_판매량예측_LSTM.ipynb',
 'h_92_대용량텍스트데이터처리.ipynb',
 'h_94_groupby_0717.ipynb',
 'h_etc.ipynb',
 'h_filter_design.ipynb',
 'h_강의개요 Part 2-3.ipynb',
 'h_참조11_액셀파일다루기.ipynb',
 'h_참조11_테이블데이터다루기(팁).ipynb',
 'h_추가할 것.ipynb',
 'h_파일리스트.ipynb',
 'haar.xml',
 'hh_17_머신러닝모델비교.ipynb',
 'hh_19_고객이탈예측.ipynb',
 'hh_20_ensemble.ipynb',
 'hh_20_앙상블알고리즘.ipynb',
 'hh_27_1_시계열 특성추가.ipynb',
 'hh_27_1_시계열 특성추가_210628.ipynb',
 'hh_29_시계열예측_자전거대여.ipynb',
 'hh_31_시계열예측모델비교.ipynb',
 'hh_33_PM_210531.ipynb',
 'hh_34_ARIMA.ipynb',
 'hh_34_LSTM_가정전력예측.ipynb',
 'hh_34_PM_LSTM.ipynb',
 'hh_34_PM_LSTM2_210418.ipynb',
 'hh_34_telemetry.ipynb',
 'hh_34_가정전기사용량EDA.ipynb',
 'hh_34_수퍼마켓판매량예측_LSTM.ipynb',
 'hh_34_시계열MLP_선형비교.ipynb',
 'hh_34_시계열_rnn_사인파.ipynb',
 'hh_34_오염예측_LSTM.ipynb',
 'hh_34_전기사용예측_prophet.ipynb',
 'hh_34_전력데이터_MS_RNN-2.ipynb',
 'hh_34_전력데이터_MS_RNN.ipynb',
 'hh_36_신경망기초_MLP_CNN.ipynb',
 'hh_37_이미지인식.ipynb',
 'hh_83_DashBoard.ipynb',
 'im-circle.png',
 'im-post.png',
 'kepco929-main',
 'lg0818-main',
 'life.ipynb',
 'make_blur_noise (1).ipynb',
 'merged_ID.csv',
 'merged_ID.txt',
 'movies.csv',
 'nh1005-main',
 'nh927-main',
 'output.csv',
 'output.xlsx',
 'output.zip',
 'output_3.zip',
 'personal_info',
 'plot_Filtering.ipynb',
 'pool.jpg',
 'pool_2.jpg',
 'ratings.csv',
 'sample.jpg',
 'sample.pdf',
 'sample.png',
 'set_angle_0402.csv',
 'shop.zip',
 'simple_merged_ID.csv',
 'simple_merged_ID2.csv',
 'smartphone_human.txt',
 'smartphone_human.txt.zip',
 'stores.csv',
 'test.csv',
 'test.ipynb',
 'test.jpg',
 'test_1.csv',
 'test_2.csv',
 'test_3.csv',
 'train.csv.zip',
 'web.ipynb',
 'yolov5',
 '공무국외여행신청-샌프란시스코-211212-수정.hwp',
 '공무국외출장계획서-김화종-샌프란시스코-211212.hwp',
 '머신러닝 사전학습(조진현님 제외)',
 '머신러닝-210909.hwp',
 '시도별 전출입 인구수.xlsx',
 '신용재_소스코드로제출.ipynb']

In [25]:
# 파일의 전체 경로, full path 만들기
cur_dir = os.getcwd()
for file_name in file_list:
    full_path = os.path.join(cur_dir, file_name)
    print(full_path)

/Users/hjk/Dropbox/lab/book12/h_02_pandas.ipynb
/Users/hjk/Dropbox/lab/book12/features.csv.zip
/Users/hjk/Dropbox/lab/book12/h_48_언어모델링.ipynb
/Users/hjk/Dropbox/lab/book12/d_03_Numpy.ipynb
/Users/hjk/Dropbox/lab/book12/cities.xlsx
/Users/hjk/Dropbox/lab/book12/f_21_StatisticsBasic.ipynb
/Users/hjk/Dropbox/lab/book12/test_1.csv
/Users/hjk/Dropbox/lab/book12/LGadd2
/Users/hjk/Dropbox/lab/book12/hh_20_앙상블알고리즘.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_오염예측_LSTM.ipynb
/Users/hjk/Dropbox/lab/book12/g_45_yolo.ipynb
/Users/hjk/Dropbox/lab/book12/g_71_1_Molecular_Visualization_using_RDkit.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_series_clustering.ipynb
/Users/hjk/Dropbox/lab/book12/A.csv
/Users/hjk/Dropbox/lab/book12/h_36_1_디지털필터출력.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_시계열_rnn_사인파.ipynb
/Users/hjk/Dropbox/lab/book12/DX_Motor.ipynb
/Users/hjk/Dropbox/lab/book12/DS-210905.hwp
/Users/hjk/Dropbox/lab/book12/hh_29_시계열예측_자전거대여.ipynb
/Users/hjk/Dropbox/lab/book12/plot_Filtering.ipynb
/Users/hjk/Dropbox/lab/book12/머신러닝-210909.hwp
/Users/hjk/Dropbox/lab/book12/make_blur_noise (1).ipynb
/Users/hjk/Dropbox/lab/book12/nh927-main
/Users/hjk/Dropbox/lab/book12/f_40_YOLO_FineTuning.ipynb
/Users/hjk/Dropbox/lab/book12/hh_33_PM_210531.ipynb
/Users/hjk/Dropbox/lab/book12/h_강의개요 Part 2-3.ipynb
/Users/hjk/Dropbox/lab/book12/fn_17_DecisionTree_RF.ipynb
/Users/hjk/Dropbox/lab/book12/h_09_테이블다루기.ipynb
/Users/hjk/Dropbox/lab/book12/smartphone_human.txt.zip
/Users/hjk/Dropbox/lab/book12/C.csv
/Users/hjk/Dropbox/lab/book12/test_2.csv
/Users/hjk/Dropbox/lab/book12/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash-master
/Users/hjk/Dropbox/lab/book12/f_16_Ranking_proba.ipynb
/Users/hjk/Dropbox/lab/book12/test_3.csv
/Users/hjk/Dropbox/lab/book12/life.ipynb
/Users/hjk/Dropbox/lab/book12/f_53_CustomerSegmentation.ipynb
/Users/hjk/Dropbox/lab/book12/B.csv
/Users/hjk/Dropbox/lab/book12/g_63_LP기초.ipynb
/Users/hjk/Dropbox/lab/book12/f_19_ModelComparison.ipynb
/Users/hjk/Dropbox/lab/book12/h_44_네이버영화평점.ipynb
/Users/hjk/Dropbox/lab/book12/hh_27_1_시계열 특성추가_210628.ipynb
/Users/hjk/Dropbox/lab/book12/f_10_TS_Forecasting.ipynb
/Users/hjk/Dropbox/lab/book12/Untitled1.ipynb
/Users/hjk/Dropbox/lab/book12/competitive-data-science-predict-future-sales
/Users/hjk/Dropbox/lab/book12/hh_34_전력데이터_MS_RNN.ipynb
/Users/hjk/Dropbox/lab/book12/f_99_Practice.ipynb
/Users/hjk/Dropbox/lab/book12/SET_angle_V2.ipynb
/Users/hjk/Dropbox/lab/book12/Refr.csv
/Users/hjk/Dropbox/lab/book12/f_48_Assignment.ipynb
/Users/hjk/Dropbox/lab/book12/.DS_Store
/Users/hjk/Dropbox/lab/book12/hh_34_전기사용예측_prophet.ipynb
/Users/hjk/Dropbox/lab/book12/Life Expectancy Data.csv
/Users/hjk/Dropbox/lab/book12/hh_37_이미지인식.ipynb
/Users/hjk/Dropbox/lab/book12/d_04_기초통계.ipynb
/Users/hjk/Dropbox/lab/book12/h_17_머신러닝모델비교_210702.ipynb
/Users/hjk/Dropbox/lab/book12/f_18_SVM.ipynb
/Users/hjk/Dropbox/lab/book12/f_56_CreditcardFraudDetection.ipynb
/Users/hjk/Dropbox/lab/book12/fn_19_Models.ipynb
/Users/hjk/Dropbox/lab/book12/f_41_opencv_face.ipynb
/Users/hjk/Dropbox/lab/book12/LS DT전문가_최종과제_취합
/Users/hjk/Dropbox/lab/book12/h_37_이미지인식_210418_ipynb.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_telemetry.ipynb
/Users/hjk/Dropbox/lab/book12/f_20_Ensemble-Copy1.ipynb
/Users/hjk/Dropbox/lab/book12/h_01_파이썬기초.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_PM_LSTM2_210418.ipynb
/Users/hjk/Dropbox/lab/book12/DS-210907-대학원-1.pdf
/Users/hjk/Dropbox/lab/book12/im-post.png
/Users/hjk/Dropbox/lab/book12/digit9-2.png
/Users/hjk/Dropbox/lab/book12/h_90_inspect_pill.ipynb
/Users/hjk/Dropbox/lab/book12/nh1005-main
/Users/hjk/Dropbox/lab/book12/merged_ID.csv
/Users/hjk/Dropbox/lab/book12/f_27_TimeseriesForecasting.ipynb
/Users/hjk/Dropbox/lab/book12/set_angle_0402.csv
/Users/hjk/Dropbox/lab/book12/32SlidingWindow2_211005_X9.ipynb
/Users/hjk/Dropbox/lab/book12/f_35_Image_Recognition.ipynb
/Users/hjk/Dropbox/lab/book12/h_추가할 것.ipynb
/Users/hjk/Dropbox/lab/book12/h_11_머신러닝개요.ipynb
/Users/hjk/Dropbox/lab/book12/h_27_1_시계열 특성추가_210701.ipynb
/Users/hjk/Dropbox/lab/book12/Untitled3.ipynb
/Users/hjk/Dropbox/lab/book12/df_sample.json
/Users/hjk/Dropbox/lab/book12/fn_13_Classification.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_전력데이터_MS_RNN-2.ipynb
/Users/hjk/Dropbox/lab/book12/Untitled.ipynb
/Users/hjk/Dropbox/lab/book12/f_13_Classification.ipynb
/Users/hjk/Dropbox/lab/book12/g_61_1_물류최적화개념.ipynb
/Users/hjk/Dropbox/lab/book12/h_19_0_다중출력회귀_210712.ipynb
/Users/hjk/Dropbox/lab/book12/h_94_groupby_0717.ipynb
/Users/hjk/Dropbox/lab/book12/g_71_5_GraphDTA_ipynb_.ipynb
/Users/hjk/Dropbox/lab/book12/HE_0722.zip
/Users/hjk/Dropbox/lab/book12/hh_34_PM_LSTM.ipynb
/Users/hjk/Dropbox/lab/book12/im-circle.png
/Users/hjk/Dropbox/lab/book12/f_12_GD.ipynb
/Users/hjk/Dropbox/lab/book12/h_34_LSTM_기본개념.ipynb
/Users/hjk/Dropbox/lab/book12/f_49_Routing.ipynb
/Users/hjk/Dropbox/lab/book12/Untitled4.ipynb
/Users/hjk/Dropbox/lab/book12/f_58_movie_generate.ipynb
/Users/hjk/Dropbox/lab/book12/output_3.zip
/Users/hjk/Dropbox/lab/book12/f_45_IntegerLP.ipynb
/Users/hjk/Dropbox/lab/book12/web.ipynb
/Users/hjk/Dropbox/lab/book12/g_60_6_비클라우팅.ipynb
/Users/hjk/Dropbox/lab/book12/test.csv
/Users/hjk/Dropbox/lab/book12/f_91_Dash.ipynb
/Users/hjk/Dropbox/lab/book12/f_46_MatrixLP.ipynb
/Users/hjk/Dropbox/lab/book12/output.zip
/Users/hjk/Dropbox/lab/book12/f_10_LinearPrediction.ipynb
/Users/hjk/Dropbox/lab/book12/hh_19_고객이탈예측.ipynb
/Users/hjk/Dropbox/lab/book12/h_03_numpy.ipynb
/Users/hjk/Dropbox/lab/book12/DS-210907-대학원-1.hwp
/Users/hjk/Dropbox/lab/book12/f_33_MLP_CNN-Copy1.ipynb
/Users/hjk/Dropbox/lab/book12/h_25_클러스터링기초.ipynb
/Users/hjk/Dropbox/lab/book12/f_57_Collaborative_Filtering.ipynb
/Users/hjk/Dropbox/lab/book12/digits-lin.pkl
/Users/hjk/Dropbox/lab/book12/hh_34_telemetry.ipynb
/Users/hjk/Dropbox/lab/book12/f_30_AddFeatures.ipynb
/Users/hjk/Dropbox/lab/book12/g_84_flask.ipynb
/Users/hjk/Dropbox/lab/book12/lg0818-main
/Users/hjk/Dropbox/lab/book12/h_14_분류순위평가.ipynb
/Users/hjk/Dropbox/lab/book12/h_32_Prophet_응용.ipynb
/Users/hjk/Dropbox/lab/book12/d_04_File.ipynb
/Users/hjk/Dropbox/lab/book12/customer.csv
/Users/hjk/Dropbox/lab/book12/f_10_LinearPrediction-RF.ipynb
/Users/hjk/Dropbox/lab/book12/.tmp.drivedownload
/Users/hjk/Dropbox/lab/book12/PM_Exersize_210805_정답.ipynb
/Users/hjk/Dropbox/lab/book12/pool.jpg
/Users/hjk/Dropbox/lab/book12/f_42_opencv_digit.ipynb
/Users/hjk/Dropbox/lab/book12/h_00_쥬피터노트북.ipynb
/Users/hjk/Dropbox/lab/book12/digit2.png
/Users/hjk/Dropbox/lab/book12/h_15_통계분석과머신러닝.ipynb
/Users/hjk/Dropbox/lab/book12/f_07_Preprocessing_Example.ipynb
/Users/hjk/Dropbox/lab/book12/h_80_웹크롤링.ipynb
/Users/hjk/Dropbox/lab/book12/credit.csv.zip
/Users/hjk/Dropbox/lab/book12/d_04_FileFolder.ipynb
/Users/hjk/Dropbox/lab/book12/fn_24_ClusteringExample.ipynb
/Users/hjk/Dropbox/lab/book12/Untitled2.ipynb
/Users/hjk/Dropbox/lab/book12/32SlidingWindow2_211005_X8.ipynb
/Users/hjk/Dropbox/lab/book12/32SlidingWindow0928update.xlsx
/Users/hjk/Dropbox/lab/book12/h_43_스팸분류.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_경사하강법구현.ipynb
/Users/hjk/Dropbox/lab/book12/hh_36_신경망기초_MLP_CNN.ipynb
/Users/hjk/Dropbox/lab/book12/f_37_LSTM.ipynb
/Users/hjk/Dropbox/lab/book12/f_03_Numpy.ipynb
/Users/hjk/Dropbox/lab/book12/g_61_2_물류최적화.ipynb
/Users/hjk/Dropbox/lab/book12/d_01_Python.ipynb
/Users/hjk/Dropbox/lab/book12/h_27_0_시계열분석기초.ipynb
/Users/hjk/Dropbox/lab/book12/Python-for-Finance-Cookbook-master
/Users/hjk/Dropbox/lab/book12/pool_2.jpg
/Users/hjk/Dropbox/lab/book12/df_excelwriter.xlsx
/Users/hjk/Dropbox/lab/book12/Untitled0.ipynb
/Users/hjk/Dropbox/lab/book12/g_46_Yolo5_ing.ipynb
/Users/hjk/Dropbox/lab/book12/digits.pkl
/Users/hjk/Dropbox/lab/book12/h_18_분류예제_포도주.ipynb
/Users/hjk/Dropbox/lab/book12/output.csv
/Users/hjk/Dropbox/lab/book12/families.jpg
/Users/hjk/Dropbox/lab/book12/fn_51_walmart-store-sales-forecasting.ipynb
/Users/hjk/Dropbox/lab/book12/f_02_Pandas.ipynb
/Users/hjk/Dropbox/lab/book12/f_36_TransferLearning.ipynb
/Users/hjk/Dropbox/lab/book12/h_82_YOLOv5_Fine_Tuning.ipynb
/Users/hjk/Dropbox/lab/book12/f_Old_walmart-sales-forecast.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_ML_overview.ipynb
/Users/hjk/Dropbox/lab/book12/f_04_File.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_SECOM_불량검출.ipynb
/Users/hjk/Dropbox/lab/book12/h_12_회귀모델.ipynb
/Users/hjk/Dropbox/lab/book12/g_71_2_DeepChem_라이브러리를_활용한Solubility_Modeling.ipynb
/Users/hjk/Dropbox/lab/book12/creditcard.csv
/Users/hjk/Dropbox/lab/book12/h_파일리스트.ipynb
/Users/hjk/Dropbox/lab/book12/cities.csv
/Users/hjk/Dropbox/lab/book12/f_09_Groupby.ipynb
/Users/hjk/Dropbox/lab/book12/h_08_탐색적분석.ipynb
/Users/hjk/Dropbox/lab/book12/__MACOSX
/Users/hjk/Dropbox/lab/book12/test.jpg
/Users/hjk/Dropbox/lab/book12/ratings.csv
/Users/hjk/Dropbox/lab/book12/yolov5
/Users/hjk/Dropbox/lab/book12/f-outlier-detection.ipynb
/Users/hjk/Dropbox/lab/book12/h_81_YOLOv5_Marking.pptx
/Users/hjk/Dropbox/lab/book12/Merged_excel.xlsx
/Users/hjk/Dropbox/lab/book12/h_81_YOLOv5_Tutorial.ipynb
/Users/hjk/Dropbox/lab/book12/f_Old_14_Ranking_PRCurve.ipynb
/Users/hjk/Dropbox/lab/book12/smartphone_human.txt
/Users/hjk/Dropbox/lab/book12/datasalon-master
/Users/hjk/Dropbox/lab/book12/haar.xml
/Users/hjk/Dropbox/lab/book12/h_46_단어벡터.ipynb
/Users/hjk/Dropbox/lab/book12/f_20_Ensemble.ipynb
/Users/hjk/Dropbox/lab/book12/h_13_분류모델.ipynb
/Users/hjk/Dropbox/lab/book12/f_59_Recommender_system_SVD.ipynb
/Users/hjk/Dropbox/lab/book12/face-detect.png
/Users/hjk/Dropbox/lab/book12/PM_train_pre.csv
/Users/hjk/Dropbox/lab/book12/shop.zip
/Users/hjk/Dropbox/lab/book12/fn_14_Ranking_PRCurve.ipynb
/Users/hjk/Dropbox/lab/book12/f_50_LP_Example.ipynb
/Users/hjk/Dropbox/lab/book12/energy.csv
/Users/hjk/Dropbox/lab/book12/DT전문가_S3사후과제_일렉트릭_박아련.ipynb
/Users/hjk/Dropbox/lab/book12/f_54_BankChurnAnalysis.ipynb
/Users/hjk/Dropbox/lab/book12/simple_merged_ID2.csv
/Users/hjk/Dropbox/lab/book12/fn_28_Prophet.ipynb
/Users/hjk/Dropbox/lab/book12/f_textbook_1.ipynb
/Users/hjk/Dropbox/lab/book12/f_25_MultiOutput.ipynb
/Users/hjk/Dropbox/lab/book12/머신러닝 사전학습(조진현님 제외)
/Users/hjk/Dropbox/lab/book12/gg_79_전력사용시계열분석.ipynb 복사본
/Users/hjk/Dropbox/lab/book12/f_39_YOLO.ipynb
/Users/hjk/Dropbox/lab/book12/g_60_8_OR_응용.ipynb
/Users/hjk/Dropbox/lab/book12/g_71_4_Pytorch를_사용한_QSAR_모델_구축Classification.ipynb
/Users/hjk/Dropbox/lab/book12/down.zip
/Users/hjk/Dropbox/lab/book12/f_11_MachineLearning.ipynb
/Users/hjk/Dropbox/lab/book12/sample.pdf
/Users/hjk/Dropbox/lab/book12/f_33_MLP_CNN.ipynb
/Users/hjk/Dropbox/lab/book12/gg_74_시계열기초LSTM.ipynb 복사본
/Users/hjk/Dropbox/lab/book12/hh_34_ARIMA.ipynb
/Users/hjk/Dropbox/lab/book12/merged_ID.txt
/Users/hjk/Dropbox/lab/book12/h_참조11_테이블데이터다루기(팁).ipynb
/Users/hjk/Dropbox/lab/book12/g_71_3_Pytorch를_사용한_QSAR_모델_구축Prediction.ipynb
/Users/hjk/Dropbox/lab/book12/f_Old_life-expectancy-who-with-several-ml-techniques.ipynb
/Users/hjk/Dropbox/lab/book12/output.xlsx
/Users/hjk/Dropbox/lab/book12/hh_34_시계열MLP_선형비교.ipynb
/Users/hjk/Dropbox/lab/book12/big.csv
/Users/hjk/Dropbox/lab/book12/sample.png
/Users/hjk/Dropbox/lab/book12/f_08_Table.ipynb
/Users/hjk/Dropbox/lab/book12/fn_0_Utility.ipynb
/Users/hjk/Dropbox/lab/book12/sample.jpg
/Users/hjk/Dropbox/lab/book12/h_참조11_액셀파일다루기.ipynb
/Users/hjk/Dropbox/lab/book12/fn_52_StockData.ipynb
/Users/hjk/Dropbox/lab/book12/personal_info
/Users/hjk/Dropbox/lab/book12/HE_Project_Examples.zip
/Users/hjk/Dropbox/lab/book12/f_02_1_Pandas_tips.ipynb
/Users/hjk/Dropbox/lab/book12/32SlidingWindow2_211005_X10.ipynb
/Users/hjk/Dropbox/lab/book12/f_05_Function.ipynb
/Users/hjk/Dropbox/lab/book12/d_02_Pandas.ipynb
/Users/hjk/Dropbox/lab/book12/h_10_시계열데이터처리.ipynb
/Users/hjk/Dropbox/lab/book12/kepco929-main
/Users/hjk/Dropbox/lab/book12/digit9.png
/Users/hjk/Dropbox/lab/book12/h_12_회귀모델_210711.ipynb
/Users/hjk/Dropbox/lab/book12/fn_23_Clustering.ipynb
/Users/hjk/Dropbox/lab/book12/f_01_Python.ipynb
/Users/hjk/Dropbox/lab/book12/f_44_LP.ipynb
/Users/hjk/Dropbox/lab/book12/h_45_형태소분석.ipynb
/Users/hjk/Dropbox/lab/book12/gold_price.csv
/Users/hjk/Dropbox/lab/book12/h_39_opencv_face-Copy1.ipynb
/Users/hjk/Dropbox/lab/book12/h_28_prophet.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_가정전기사용량EDA.ipynb
/Users/hjk/Dropbox/lab/book12/f_51_GoldPriceipynb.ipynb
/Users/hjk/Dropbox/lab/book12/32SlidingWindow2-210915.ipynb
/Users/hjk/Dropbox/lab/book12/h_34_시계열_rnn_전력사용예측.ipynb
/Users/hjk/Dropbox/lab/book12/공무국외여행신청-샌프란시스코-211212-수정.hwp
/Users/hjk/Dropbox/lab/book12/h_42_뉴스기사분석.ipynb
/Users/hjk/Dropbox/lab/book12/g_60_7_라우팅고급.ipynb
/Users/hjk/Dropbox/lab/book12/.ipynb_checkpoints
/Users/hjk/Dropbox/lab/book12/f_06_Preprocessing.ipynb
/Users/hjk/Dropbox/lab/book12/h_33_PM_210717.ipynb
/Users/hjk/Dropbox/lab/book12/h_83_Dash소개.ipynb
/Users/hjk/Dropbox/lab/book12/chromedriver
/Users/hjk/Dropbox/lab/book12/h_19_1_다중출력회귀시계열_210712.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_총판매량예측_prophet.ipynb
/Users/hjk/Dropbox/lab/book12/eCar.csv
/Users/hjk/Dropbox/lab/book12/h_etc.ipynb
/Users/hjk/Dropbox/lab/book12/h_24_Imbalance_CreditCard.ipynb
/Users/hjk/Dropbox/lab/book12/hh_34_수퍼마켓판매량예측_LSTM.ipynb
/Users/hjk/Dropbox/lab/book12/f_55_DefaultPrediction.ipynb
/Users/hjk/Dropbox/lab/book12/f_22_FeatureEngineering.ipynb
/Users/hjk/Dropbox/lab/book12/fn_11_Regression.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_Autoencoders_MNIST.ipynb
/Users/hjk/Dropbox/lab/book12/h_21_XGBoost_LightGBM_0704.ipynb
/Users/hjk/Dropbox/lab/book12/Project_Life_Expectancy.ipynb
/Users/hjk/Dropbox/lab/book12/h_26_클러스터링_최적_k.ipynb
/Users/hjk/Dropbox/lab/book12/h_47_IMDB_Embedding.ipynb
/Users/hjk/Dropbox/lab/book12/fn_27_TimeseriesForecasting.ipynb
/Users/hjk/Dropbox/lab/book12/h_35_시퀀스패턴분류_210703_.ipynb
/Users/hjk/Dropbox/lab/book12/face-pickup.png
/Users/hjk/Dropbox/lab/book12/f_43_object_detect.ipynb
/Users/hjk/Dropbox/lab/book12/h_04_파일다루기.ipynb
/Users/hjk/Dropbox/lab/book12/hh_27_1_시계열 특성추가.ipynb
/Users/hjk/Dropbox/lab/book12/h_23_차원축소_특성공학.ipynb
/Users/hjk/Dropbox/lab/book12/Hands-on-Python-for-Finance-master
/Users/hjk/Dropbox/lab/book12/신용재_소스코드로제출.ipynb
/Users/hjk/Dropbox/lab/book12/movies.csv
/Users/hjk/Dropbox/lab/book12/fn_15_LogisticRegression.ipynb
/Users/hjk/Dropbox/lab/book12/h_16_로지스틱회귀.ipynb
/Users/hjk/Dropbox/lab/book12/f_47_Constraint.ipynb
/Users/hjk/Dropbox/lab/book12/f_38_LSTM_TimeSeries.ipynb
/Users/hjk/Dropbox/lab/book12/h_20_앙상블알고리즘_0624.ipynb
/Users/hjk/Dropbox/lab/book12/Gold Prices.xlsx
/Users/hjk/Dropbox/lab/book12/hh_17_머신러닝모델비교.ipynb
/Users/hjk/Dropbox/lab/book12/PM_Exersize_210805.ipynb
/Users/hjk/Dropbox/lab/book12/f_29_ProphetAdvanced.ipynb
/Users/hjk/Dropbox/lab/book12/hh_31_시계열예측모델비교.ipynb
/Users/hjk/Dropbox/lab/book12/data
/Users/hjk/Dropbox/lab/book12/h_05_함수사용.ipynb
/Users/hjk/Dropbox/lab/book12/h_90_판매량예측_LSTM.ipynb
/Users/hjk/Dropbox/lab/book12/g_81_스트링_객체변환.ipynb
/Users/hjk/Dropbox/lab/book12/공무국외출장계획서-김화종-샌프란시스코-211212.hwp
/Users/hjk/Dropbox/lab/book12/simple_merged_ID.csv
/Users/hjk/Dropbox/lab/book12/LGadd2.zip
/Users/hjk/Dropbox/lab/book12/f_90_opencv_perspective.ipynb
/Users/hjk/Dropbox/lab/book12/test.ipynb
/Users/hjk/Dropbox/lab/book12/h_06_데이터전처리.ipynb
/Users/hjk/Dropbox/lab/book12/h_38_전이학습.ipynb
/Users/hjk/Dropbox/lab/book12/h_34_1_MLP_CNN_210418.ipynb
/Users/hjk/Dropbox/lab/book12/h_04_1_파일다루기연습.ipynb
/Users/hjk/Dropbox/lab/book12/train.csv.zip
/Users/hjk/Dropbox/lab/book12/hh_34_LSTM_가정전력예측.ipynb
/Users/hjk/Dropbox/lab/book12/h_92_대용량텍스트데이터처리.ipynb
/Users/hjk/Dropbox/lab/book12/hh_83_DashBoard.ipynb
/Users/hjk/Dropbox/lab/book12/aa_08_Boston_Opt.ipynb
/Users/hjk/Dropbox/lab/book12/f_15_LogisticRegression.ipynb
/Users/hjk/Dropbox/lab/book12/f_32_PM.ipynb
/Users/hjk/Dropbox/lab/book12/32SlidingWindow2.xlsx
/Users/hjk/Dropbox/lab/book12/h_31_자전거대여수예측_0701.ipynb
/Users/hjk/Dropbox/lab/book12/g_54_토픽모델링.ipynb
/Users/hjk/Dropbox/lab/book12/f_34_PatternRecognition.ipynb
/Users/hjk/Dropbox/lab/book12/stores.csv
/Users/hjk/Dropbox/lab/book12/down2.zip
/Users/hjk/Dropbox/lab/book12/TV.csv
/Users/hjk/Dropbox/lab/book12/f_26_TimeseriesOutput.ipynb
/Users/hjk/Dropbox/lab/book12/NGdata1.zip
/Users/hjk/Dropbox/lab/book12/h_filter_design.ipynb
/Users/hjk/Dropbox/lab/book12/f_31_XY_Model.ipynb
/Users/hjk/Dropbox/lab/book12/f_91_Recommendation_surprise.ipynb
/Users/hjk/Dropbox/lab/book12/h_07_데이터전처리실습.ipynb
/Users/hjk/Dropbox/lab/book12/hh_20_ensemble.ipynb
/Users/hjk/Dropbox/lab/book12/시도별 전출입 인구수.xlsx

## 폴더 찾기
- 폴더인지를 검사하는 isdir() 함수 사용

In [26]:
for file_name in file_list:
    if os.path.isdir(file_name):
        print("폴더:", file_name)

폴더: LGadd2
폴더: nh927-main
폴더: Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash-master
폴더: competitive-data-science-predict-future-sales
폴더: LS DT전문가_최종과제_취합
폴더: nh1005-main
폴더: lg0818-main
폴더: .tmp.drivedownload
폴더: Python-for-Finance-Cookbook-master
폴더: __MACOSX
폴더: yolov5
폴더: datasalon-master
폴더: 머신러닝 사전학습(조진현님 제외)
폴더: personal_info
폴더: kepco929-main
폴더: .ipynb_checkpoints
폴더: Hands-on-Python-for-Finance-master
폴더: data

## (연습) 랜덤넘버를 생성하는 센서 3개의 출력 100개를 csv, zip 파일로 만들기
- 랜덤넘버를 (100,3) 구조로 만들고 이를 csv 및 zip 파일로 만든다
- 힌트: random.rand(100,3)으로 2차원 랜덤넘버를 생성할 수 있다

In [27]:
# (풀이)

## 기타 폴더 및 파일 관리 함수
- os 패키지에서 제공하는 함수
 - 폴더 생성 mkdir()
 - 폴더 위치 이동 chdir()
 - 파일 이름 변경 rename()
 - 파일 삭제 remove()
 - 폴더 삭제 rmdir()

In [28]:
# 폴더가 없으면 새로 만들기
if not os.path.exists("./data_tmp"):
    os.mkdir("./data_tmp")

In [29]:
# (참고) 폴더가 있으면 "지우고" 새로 만들기
if os.path.exists("./data_tmp"):
    os.rmdir("./data_tmp")
    os.mkdir("./data_tmp")

In [30]:
# 폴더 이동
os.chdir('./data_tmp')

In [31]:
os.getcwd()

'/Users/hjk/Dropbox/lab/book12/data_tmp'

In [32]:
# 폴더 이동
os.chdir('../')

In [33]:
os.getcwd()

'/Users/hjk/Dropbox/lab/book12'

In [34]:
# 파일 이름 변경
os.rename('output.csv','new_output.csv')
with open('new_output.csv') as f: print(f.read())

0.0,1.0,2.0,3.0,4.0
5.0,6.0,7.0,8.0,9.0
10.0,11.0,12.0,13.0,14.0
15.0,16.0,17.0,18.0,19.0
20.0,21.0,22.0,23.0,24.0
25.0,26.0,27.0,28.0,29.0
30.0,31.0,32.0,33.0,34.0
35.0,36.0,37.0,38.0,39.0
40.0,41.0,42.0,43.0,44.0
45.0,46.0,47.0,48.0,49.0

In [35]:
# 파일 삭제
os.remove('new_output.csv')

In [36]:
# 폴더 삭제
os.rmdir('./data_tmp')

## (연습) 현재 폴더에서 test로 시작하는 파일명으로 모두 t_test로 시작하는 이름으로 변경

In [37]:
# (풀이)

## (연습) 현재 폴더에서 t_test로 시작하는 파일명으로 모두 test로 시작하는 이름으로 변경

In [38]:
# (풀이)

# 정답

## (연습) 랜덤넘버를 생성하는 센서 3개의 출력 100개를 csv, zip 파일로 만들기
- 랜덤넘버를 (100,3) 구조로 만들고 이를 csv 및 zip 파일로 만든다
- 힌트: random.rand(100,3)으로 2차원 랜덤넘버를 생성할 수 있다

In [39]:
x = np.random.rand(100,3)
x[:5]

array([[0.70915461, 0.33128823, 0.76599516],
       [0.36978895, 0.54839227, 0.31758868],
       [0.0735438 , 0.97667148, 0.82913036],
       [0.65087652, 0.57024871, 0.18733589],
       [0.34298556, 0.10352711, 0.78348176]])

In [40]:
np.savetxt("test_3.csv", x, delimiter=",")
# 저장 확인
df = pd.read_csv('test_3.csv', header=None)  
df

           0         1         2
0   0.709155  0.331288  0.765995
1   0.369789  0.548392  0.317589
2   0.073544  0.976671  0.829130
3   0.650877  0.570249  0.187336
4   0.342986  0.103527  0.783482
..       ...       ...       ...
95  0.186380  0.317175  0.584919
96  0.691522  0.605399  0.328059
97  0.516537  0.351971  0.802015
98  0.507388  0.821044  0.696439
99  0.534160  0.109166  0.714470

[100 rows x 3 columns]

In [41]:
# 압축하기
with zipfile.ZipFile('output_3.zip', 'w') as z:
    z.write('test_3.csv')

In [42]:
# 확인
df = pd.read_csv('output_3.zip', header=None)  
df

           0         1         2
0   0.709155  0.331288  0.765995
1   0.369789  0.548392  0.317589
2   0.073544  0.976671  0.829130
3   0.650877  0.570249  0.187336
4   0.342986  0.103527  0.783482
..       ...       ...       ...
95  0.186380  0.317175  0.584919
96  0.691522  0.605399  0.328059
97  0.516537  0.351971  0.802015
98  0.507388  0.821044  0.696439
99  0.534160  0.109166  0.714470

[100 rows x 3 columns]

## (연습) 현재 폴더에서 test로 시작하는 파일명으로 모두 t_test로 시작하는 이름으로 변경

In [43]:
from glob import glob
f_list = glob('test*')
f_list

['test_1.csv',
 'test_2.csv',
 'test_3.csv',
 'test.csv',
 'test.jpg',
 'test.ipynb']

In [44]:
for file in f_list:
    os.rename(file, 't_'+file)

glob('t_*')

['t_test.jpg',
 't_test.ipynb',
 't_test.csv',
 't_test_3.csv',
 't_test_2.csv',
 't_test_1.csv']

## (연습) 현재 폴더에서 t_test로 시작하는 파일명으로 모두 test로 시작하는 이름으로 변경

In [45]:
from glob import glob
f_list = glob('t_test*')
f_list

['t_test.jpg',
 't_test.ipynb',
 't_test.csv',
 't_test_3.csv',
 't_test_2.csv',
 't_test_1.csv']

In [46]:
for file in f_list:
    os.rename(file, file[2:])
glob('test*')

['test_1.csv',
 'test_2.csv',
 'test_3.csv',
 'test.csv',
 'test.jpg',
 'test.ipynb']